apiVersion: v2
name: ecoharmonogram-api
description: FastAPI service for Ecoharmonogram schedule data
type: application
version: 1.0.2
appVersion: "1.0.2"
keywords:
  - ecoharmonogram
  - fastapi
  - waste
home: https://github.com/meloos/ecoharmonogram-api
sources:
  - https://github.com/meloos/ecoharmonogram-api
maintainers:
  - name: Michal Lemke
    email: contact@michallemke.com
